### ISSUE TITLE
regular fidget spinners spin always

### ISSUE THREAD

**Issue by sythel** [andrew-boutin/idle-fidget-spinners-web-ui#1]
indicates they are active even thought they aint be yanno wwwwwwwwwwwwowwwwwwwwwwwwwwwwwwwwwwwwwwwww kill it with fire @sythel 🗡 💃

**Comment by sythel** [comment]
also some weird margin or something happening with normal spinner

**Comment by GregHilston** [comment]
also, i hear by award @andrew-boutin a 🥇  for this project

**Comment by sythel** [comment]
fake news awards are still awards

**Comment by andrew-boutin** [comment]
Yeah I plan on making the regular spinners spin when clicked and then slow down and stop eventually. Also the auto spinners will be able to spin faster when clicked and slow down to their auto spin speed after not being clicked for a few.

**Comment by andrew-boutin** [comment]
Not sure about the margin issue you mentioned? Can you get a screenshot?

**Comment by sythel** [comment]
![screenshot-2018-1-22 title](https://user-images.githubusercontent.com/4307418/35246903-60e9b10c-ff96-11e7-92bf-1ffcb9021978.png)
without the vertial-align

**Comment by andrew-boutin** [comment]
Cool thanks for fixing that!

**Comment by andrew-boutin** [comment]
The regular spinners only spin now when you click on them 🌮
